import type { Config } from 'tailwindcss'

export default {
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        'surface-dim': '#cbdbf5',
        tertiary: '#5f4100',
        'on-tertiary-fixed': '#271900',
        'on-surface-variant': '#434652',
        'surface-bright': '#f8f9ff',
        background: '#f8f9ff',
        surface: '#f8f9ff',
        'on-tertiary-fixed-variant': '#5f4100',
        error: '#ba1a1a',
        'tertiary-container': '#7d5700',
        'primary-container': '#6c8eef',
        'surface-container-high': '#dce9ff',
        'on-primary-fixed': '#00174a',
        'on-surface': '#0b1c30',
        'inverse-surface': '#213145',
        primary: '#13409e',
        'tertiary-fixed-dim': '#f1be65',
        'surface-container-highest': '#d3e4fe',
        'inverse-on-surface': '#eaf1ff',
        'outline-variant': '#c4c6d4',
        'inverse-primary': '#b4c5ff',
        'on-secondary-fixed-variant': '#4f4065',
        'lens-glow': 'rgba(52, 89, 183, 0.15)',
        'on-tertiary': '#ffffff',
        'on-primary-fixed-variant': '#13409e',
        'secondary-container': '#e3cffd',
        'on-secondary': '#ffffff',
        'on-error-container': '#93000a',
        'on-error': '#ffffff',
        'on-background': '#0b1c30',
        'on-primary-container': '#cdd8ff',
        'primary-fixed-dim': '#b4c5ff',
        'surface-container-low': '#eff4ff',
        'surface-tint': '#3459b7',
        'secondary-fixed-dim': '#d2beeb',
        'tertiary-fixed': '#ffdeaa',
        outline: '#747683',
        'glass-bg': 'rgba(255, 255, 255, 0.8)',
        'surface-container': '#e5eeff',
        'secondary-fixed': '#eddcff',
        'on-secondary-container': '#66567d',
        'surface-variant': '#d3e4fe',
        'on-secondary-fixed': '#221437',
        'primary-fixed': '#dbe1ff',
        'surface-container-lowest': '#ffffff',
        'on-tertiary-container': '#ffd287',
        secondary: '#67577e',
        'on-primary': '#ffffff',
        'error-container': '#ffdad6',
      },
      borderRadius: {
        DEFAULT: '1rem',
        lg: '2rem',
        xl: '3rem',
        full: '9999px',
      },
      spacing: {
        'container-margin': '24px',
        'layout-max-width': '1280px',
        base: '8px',
        'section-gap': '48px',
        gutter: '16px',
      },
      fontFamily: {
        'body-md': ['Plus Jakarta Sans', 'sans-serif'],
        'headline-lg-mobile': ['Plus Jakarta Sans', 'sans-serif'],
        'body-lg': ['Plus Jakarta Sans', 'sans-serif'],
        'headline-xl': ['Plus Jakarta Sans', 'sans-serif'],
        'headline-lg': ['Plus Jakarta Sans', 'sans-serif'],
        'label-md': ['Plus Jakarta Sans', 'sans-serif'],
        'headline-md': ['Plus Jakarta Sans', 'sans-serif'],
        'label-sm': ['Plus Jakarta Sans', 'sans-serif'],
      },
      fontSize: {
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'headline-lg-mobile': ['28px', { lineHeight: '36px', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'headline-xl': ['40px', { lineHeight: '48px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'label-md': ['14px', { lineHeight: '20px', letterSpacing: '0.01em', fontWeight: '600' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'label-sm': ['12px', { lineHeight: '16px', fontWeight: '500' }],
      },
      boxShadow: {
        'ambient-1': '0 4px 20px rgba(52, 89, 183, 0.05)',
      },
    },
  },
  plugins: [],
} satisfies Config

